import type { Subject } from "./types";

/**
 * A topic entry in the curriculum catalog.
 *
 *   label   — short chapter name shown in the dropdown.
 *   limits  — optional scope description fed to the AI in the topic value
 *             (after an em-dash separator). Use this to spell out exactly
 *             what's in/out of the program for the chosen section so the
 *             AI doesn't generate exercises beyond the syllabus.
 */
export interface TopicEntry {
  label: string;
  limits: string;
}
export type Topic = string | TopicEntry;

/**
 * Curriculum topic catalog: country × subject × grade level [× section] → ordered list.
 *
 * Lookup precedence (handled by `topicsFor`):
 *   1. `${COUNTRY}_${subject}_${level}_${section}` — section-specific (preferred)
 *   2. `${COUNTRY}_${subject}_${level}`           — level default (any section)
 *   3. `${COUNTRY}_${subject}`                    — country/subject default
 *   4. `[]`                                       — caller falls back to free-text
 *
 * Entries may be either plain strings (legacy, no scope description) or
 * `TopicEntry` objects with explicit program-limit descriptions. The picker
 * appends the `limits` string to the option value so the AI receives the
 * scope context along with the chapter name.
 *
 * Topics are listed in the order chapters typically appear in the country's
 * official syllabus so the dropdown reads as a table of contents.
 */
const TOPICS: Record<string, Topic[]> = {
  // ── FRANCE ────────────────────────────────────────────────────────────────
  "FR_math_Terminale": [
    "Suites numériques (limites, monotonie)",
    "Limites de fonctions",
    "Continuité",
    "Compléments sur la dérivation",
    "Convexité",
    "Fonction logarithme népérien",
    "Fonction exponentielle",
    "Primitives et intégration",
    "Vecteurs et géométrie dans l'espace",
    "Produit scalaire dans l'espace",
    "Probabilités conditionnelles",
    "Variables aléatoires (espérance, variance)",
    "Loi binomiale",
    "Loi des grands nombres",
    "Combinatoire et dénombrement",
    "Algorithmique (Python)",
  ],
  "FR_math_Première": [
    "Second degré",
    "Suites arithmétiques et géométriques",
    "Dérivation",
    "Variations et extremums",
    "Fonctions trigonométriques",
    "Fonction exponentielle (introduction)",
    "Géométrie repérée",
    "Produit scalaire dans le plan",
    "Probabilités conditionnelles",
    "Variables aléatoires",
    "Loi binomiale (introduction)",
  ],
  "FR_physics_Terminale": [
    "Mouvements et lois de Newton",
    "Mouvements dans un champ uniforme (gravitation, électrique)",
    "Aspects énergétiques (cinétique, potentielle, mécanique)",
    "Mouvement d'un satellite, lois de Kepler",
    "Ondes mécaniques progressives",
    "Effet Doppler",
    "Interférences et diffraction",
    "Modèle ondulatoire de la lumière",
    "Modèle particulaire — effet photoélectrique",
    "Niveaux d'énergie atomique, lasers",
    "Décroissance radioactive",
    "Désintégrations nucléaires, énergie de liaison",
    "Évolution d'un système — bilans énergétiques",
  ],
  "FR_chemistry_Terminale": [
    "Réactions acide-base, pH, Ke",
    "Constantes d'acidité Ka et diagrammes",
    "Réactions d'oxydoréduction",
    "Pile et électrolyse",
    "Solubilité, produit de solubilité Ks",
    "Cinétique chimique (vitesse, ordre, loi d'Arrhenius)",
    "Mécanismes réactionnels (flèches courbes)",
    "Stéréoisomérie (chiralité, énantiomères)",
    "Spectroscopie IR et RMN",
    "Synthèse organique multi-étapes",
    "Dosages par titrage (acide-base, redox)",
  ],
  "FR_informatics_Terminale": [
    "Structures de données : pile, file",
    "Récursivité",
    "Programmation orientée objet (POO)",
    "Algorithmes de tri (tri fusion, tri rapide)",
    "Diviser pour régner",
    "Programmation dynamique",
    "Algorithmes de graphe : BFS, DFS",
    "Algorithme de Dijkstra",
    "Bases de données relationnelles, SQL",
    "Systèmes d'exploitation, processus",
    "Réseaux : routage, TCP/IP",
    "Protocoles HTTP / HTTPS",
  ],

  // ── MOROCCO ────────────────────────────────────────────────────────────────
  "MA_math_2ème Bac": [
    "Limites et continuité",
    "Dérivabilité",
    "Étude de fonctions",
    "Fonction logarithme népérien",
    "Fonction exponentielle",
    "Suites numériques",
    "Calcul intégral",
    "Équations différentielles",
    "Nombres complexes",
    "Géométrie dans l'espace",
    "Probabilités",
    "Dénombrement",
    "Arithmétique dans ℤ (PGCD, congruences)",
    "Structures algébriques (PC/SVT)",
  ],
  "MA_math_1ère Bac": [
    "Généralités sur les fonctions",
    "Limites et continuité (introduction)",
    "Dérivation",
    "Étude de fonctions polynômes et rationnelles",
    "Suites numériques",
    "Trigonométrie",
    "Géométrie analytique",
    "Produit scalaire",
    "Statistiques",
    "Probabilités",
  ],
  "MA_physics_2ème Bac": [
    "Mécanique : forces, champ de pesanteur",
    "Lois de Newton, mouvements rectiligne et circulaire",
    "Mouvements dans les champs (g = 10 m/s²)",
    "Oscillateurs mécaniques",
    "Ondes mécaniques",
    "Ondes lumineuses, diffraction",
    "Décroissance radioactive",
    "Réactions nucléaires (fission, fusion)",
    "Dipôle RC, RL et RLC",
    "Modulation et démodulation",
  ],
  "MA_chemistry_2ème Bac": [
    "Cinétique chimique",
    "Équilibre chimique, quotient de réaction",
    "Réactions acide-base, pH",
    "Constantes d'acidité Ka, diagrammes",
    "Réactions d'oxydoréduction",
    "Pile et électrolyse",
    "Dosages",
    "Chimie organique : groupes fonctionnels",
    "Mécanismes réactionnels",
  ],
  "MA_informatics_2ème Bac": [
    "Algorithmique : structures de contrôle",
    "Structures de données : tableaux, listes",
    "Procédures et fonctions",
    "Récursivité (introduction)",
    "Tri et recherche",
    "Bases de données, SQL (introduction)",
    "Programmation Python",
  ],

  // ── TUNISIA ────────────────────────────────────────────────────────────────
  "TN_math_4ème (Bac)": [
    "Suites numériques",
    "Limites et continuité",
    "Dérivabilité",
    "Fonction logarithme népérien",
    "Fonction exponentielle",
    "Calcul intégral et primitives",
    "Équations différentielles",
    "Nombres complexes",
    "Géométrie dans l'espace",
    "Probabilités conditionnelles",
    "Loi binomiale",
    "Arithmétique (divisibilité, congruences)",
  ],
  "TN_physics_4ème (Bac)": [
    "Mécanique : lois de Newton",
    "Mouvement dans un champ de pesanteur (g = 10 m/s²)",
    "Mouvement dans un champ électrique",
    "Oscillations mécaniques",
    "Ondes mécaniques progressives",
    "Ondes lumineuses",
    "Dipôle RC, RL, RLC",
    "Oscillations électriques libres et forcées",
    "Réactions nucléaires, désintégration",
  ],
  "TN_chemistry_4ème (Bac)": [
    "Cinétique chimique",
    "Équilibre chimique",
    "Réactions acide-base, pH, Ke",
    "Solutions tampons",
    "Réactions d'oxydoréduction",
    "Pile et électrolyse",
    "Dosages acide-base et redox",
    "Chimie organique : alcools, acides, esters",
  ],
  "TN_informatics_4ème (Bac)": [
    "Algorithmique : DEBUT/FIN, SI/ALORS, TANTQUE/FAIRE",
    "Types de données : ENTIER, REEL, CHAINE, BOOLEEN",
    "Tableaux et matrices",
    "PROCEDURE et FONCTION",
    "Récursivité",
    "Algorithmes de tri (tri à bulles, tri par sélection)",
    "Algorithmes de recherche",
    "Pascal : programmation structurée",
    "Python : initiation",
    "Bases de données, SQL",
  ],

  // ── UNITED STATES ──────────────────────────────────────────────────────────
  "US_math_Grade 12 (AP)": [
    "Limits and continuity",
    "Differentiation: rules and applications",
    "Implicit differentiation, related rates",
    "Mean Value Theorem",
    "Optimization problems",
    "Integration and Fundamental Theorem of Calculus",
    "Techniques of integration (u-sub, parts, partial fractions)",
    "Applications of integration (area, volume)",
    "Differential equations (separable)",
    "Sequences and series (BC)",
    "Taylor and Maclaurin series (BC)",
    "Parametric, polar, and vector functions (BC)",
  ],
  "US_math_Grade 11": [
    "Polynomial and rational functions",
    "Exponential and logarithmic functions",
    "Trigonometric functions and identities",
    "Conic sections",
    "Sequences and series",
    "Vectors and matrices",
    "Probability and combinatorics",
    "Statistics: distributions",
    "Limits (intro to calculus)",
  ],
  "US_physics_Grade 12 (AP)": [
    "Kinematics in 1D and 2D",
    "Newton's laws and applications",
    "Work, energy, and power",
    "Linear momentum and collisions",
    "Circular motion and gravitation",
    "Rotational motion and torque",
    "Simple harmonic motion",
    "Mechanical waves and sound",
    "Electrostatics and Coulomb's law",
    "DC circuits",
    "Magnetic fields and forces",
    "Electromagnetic induction (AP Physics C)",
  ],
  "US_chemistry_Grade 12 (AP)": [
    "Atomic structure and periodicity",
    "Chemical bonding (Lewis, VSEPR, hybridization)",
    "Stoichiometry and reactions",
    "Thermochemistry (ΔH, Hess's law)",
    "Kinetics (rate laws, Arrhenius)",
    "Chemical equilibrium (Kc, Kp)",
    "Acid-base equilibria, Ka/Kb, Kw",
    "Buffers and titrations",
    "Solubility equilibria, Ksp",
    "Thermodynamics (ΔG, ΔS, spontaneity)",
    "Electrochemistry, standard potentials",
  ],
  "US_informatics_Grade 12 (AP)": [
    "Java syntax and primitive types",
    "Classes and objects (OOP)",
    "Inheritance and polymorphism",
    "ArrayLists and 2D arrays",
    "Recursion",
    "Searching algorithms (linear, binary)",
    "Sorting algorithms (selection, insertion, merge)",
    "Iteration over data structures",
    "Algorithm analysis (informal)",
  ],

  // ── UNITED KINGDOM ─────────────────────────────────────────────────────────
  "GB_math_A-level": [
    "Algebraic methods (proof, surds, indices)",
    "Coordinate geometry, equation of a circle",
    "Trigonometric identities and equations",
    "Differentiation (product, quotient, chain)",
    "Integration techniques",
    "Sequences and series, binomial expansion",
    "Exponentials and logarithms",
    "Vectors in 3D",
    "Numerical methods (Newton-Raphson)",
    "Probability and statistics",
    "Hypothesis testing",
    "Mechanics: kinematics and Newton's laws",
    "Mechanics: moments and statics",
  ],
  "GB_physics_A-level": [
    "Mechanics: forces, motion, energy",
    "Materials: Hooke's law, Young's modulus",
    "Waves: progressive, stationary, interference",
    "Diffraction and refraction",
    "Quantum phenomena: photoelectric effect",
    "Electricity: circuits, Kirchhoff's laws",
    "Electric fields and capacitance",
    "Magnetic fields and induction",
    "Nuclear physics: radioactivity, decay",
    "Thermal physics, ideal gas",
    "Astrophysics or Medical Physics (option)",
    "Special relativity (Edexcel/AQA)",
  ],
  "GB_chemistry_A-level": [
    "Atomic structure and bonding",
    "Energetics (enthalpy, Hess's law)",
    "Kinetics, Arrhenius equation",
    "Equilibria: Kc, Kp, Le Chatelier",
    "Acids and bases, Kw, buffers",
    "Redox and electrochemistry",
    "Periodicity, transition metals",
    "Organic: alkanes, alkenes, halogenoalkanes",
    "Organic mechanisms (curly arrows: SN1, SN2, E1, E2)",
    "Aromatic chemistry, electrophilic substitution",
    "Carbonyls, carboxylic acids, esters",
    "Spectroscopy: IR, NMR, mass spec",
  ],
  "GB_informatics_A-level": [
    "Programming fundamentals (Python)",
    "Data structures: lists, stacks, queues, trees",
    "Algorithms: sorting, searching",
    "Big-O complexity analysis",
    "Boolean algebra, logic gates",
    "Finite state machines, Turing machines",
    "Databases and SQL",
    "Networking: TCP/IP, OSI model",
    "Object-oriented programming",
    "Recursion",
  ],

  // ── GERMANY ────────────────────────────────────────────────────────────────
  "DE_math_Abitur": [
    "Analysis: Funktionen, Grenzwerte",
    "Ableitungen und Kurvendiskussion",
    "Integralrechnung",
    "Exponential- und Logarithmusfunktionen",
    "Analytische Geometrie: Vektoren im Raum",
    "Geraden und Ebenen",
    "Skalarprodukt, Abstandsberechnungen",
    "Stochastik: Wahrscheinlichkeit",
    "Binomial- und Normalverteilung",
    "Hypothesentests",
    "Matrizen (in einigen Bundesländern)",
  ],
  "DE_physics_Abitur": [
    "Mechanik: Kinematik und Dynamik",
    "Energie und Impuls",
    "Schwingungen und Wellen",
    "Elektromagnetismus, Felder",
    "Induktion",
    "Quantenphysik: Photoeffekt, Materiewellen",
    "Atomphysik, Energieniveaus",
    "Spezielle Relativitätstheorie",
    "Kernphysik",
  ],
  "DE_chemistry_Abitur": [
    "Atombau und Periodensystem",
    "Chemische Bindung",
    "Reaktionen und Energetik",
    "Säuren und Basen, pH",
    "Redoxreaktionen, Elektrochemie",
    "Chemisches Gleichgewicht",
    "Kinetik",
    "Organische Chemie: Funktionalitäten",
    "Reaktionsmechanismen",
  ],
  "DE_informatics_Abitur": [
    "Objektorientierte Programmierung (Java)",
    "Datenstrukturen: Listen, Bäume, Graphen",
    "Algorithmen und Komplexität",
    "Relationale Datenbanken, SQL",
    "Endliche Automaten",
    "Formale Sprachen (Chomsky-Hierarchie)",
    "Turingmaschinen",
    "Netzwerke und Sicherheit",
  ],

  // ── ITALY ──────────────────────────────────────────────────────────────────
  "IT_math_5ª Liceo Scientifico": [
    "Limiti di funzioni",
    "Continuità",
    "Derivate e teoremi del calcolo differenziale",
    "Teorema di De L'Hôpital",
    "Studio di funzione",
    "Integrali indefiniti e definiti",
    "Calcolo combinatorio",
    "Probabilità",
    "Geometria analitica nello spazio",
    "Equazioni differenziali",
    "Numeri complessi",
  ],
  "IT_physics_5ª Liceo Scientifico": [
    "Elettrostatica e campo elettrico",
    "Potenziale elettrico, condensatori",
    "Corrente elettrica, leggi di Ohm",
    "Campo magnetico, forza di Lorentz",
    "Induzione elettromagnetica",
    "Onde elettromagnetiche",
    "Relatività ristretta",
    "Fisica quantistica (introduzione)",
    "Effetto fotoelettrico",
    "Modelli atomici",
    "Fisica nucleare",
  ],
  "IT_chemistry_5ª Liceo Scientifico": [
    "Struttura atomica e tavola periodica",
    "Legami chimici",
    "Termochimica",
    "Cinetica chimica",
    "Equilibrio chimico",
    "Acidi e basi, pH",
    "Elettrochimica",
    "Chimica organica: idrocarburi",
    "Gruppi funzionali, biomolecole",
  ],

  // ── SPAIN ──────────────────────────────────────────────────────────────────
  "ES_math_2º Bachillerato": [
    "Álgebra: matrices y determinantes",
    "Sistemas de ecuaciones lineales",
    "Geometría en el espacio (vectores, rectas, planos)",
    "Límites y continuidad",
    "Derivadas y aplicaciones",
    "Estudio de funciones",
    "Integrales indefinidas y definidas",
    "Aplicaciones de la integral",
    "Probabilidad condicionada, Bayes",
    "Distribuciones (binomial, normal)",
    "Inferencia estadística",
  ],
  "ES_physics_2º Bachillerato": [
    "Gravitación universal",
    "Campo gravitatorio",
    "Movimiento ondulatorio",
    "Óptica geométrica y física",
    "Campo eléctrico, potencial",
    "Campo magnético, inducción",
    "Física cuántica (efecto fotoeléctrico, dualidad)",
    "Relatividad especial",
    "Física nuclear",
  ],
  "ES_chemistry_2º Bachillerato": [
    "Estructura atómica, configuración electrónica",
    "Enlace químico",
    "Termoquímica",
    "Cinética química",
    "Equilibrio químico",
    "Reacciones ácido-base, pH",
    "Reacciones de oxidación-reducción",
    "Electroquímica",
    "Química orgánica: nomenclatura, isomería",
    "Reacciones orgánicas (tipos generales)",
    "Polímeros y biomoléculas",
  ],

  // ── EGYPT ──────────────────────────────────────────────────────────────────
  "EG_math_Grade 12 (Thanaweya Amma)": [
    "Algebra and complex numbers",
    "Trigonometry and identities",
    "Analytic geometry (3D)",
    "Differential calculus",
    "Applications of derivatives",
    "Integral calculus",
    "Differential equations (introduction)",
    "Statistics and probability",
  ],
  "EG_physics_Grade 12 (Thanaweya Amma)": [
    "Mechanics: dynamics and Newton's laws",
    "Work, energy, power",
    "Waves and sound",
    "Geometric optics",
    "Electrostatics, capacitors",
    "Current electricity",
    "Magnetism and electromagnetic induction",
    "Modern physics (photoelectric, atomic models)",
    "Nuclear physics",
  ],
  "EG_chemistry_Grade 12 (Thanaweya Amma)": [
    "Periodic table and atomic structure",
    "Chemical bonding",
    "Stoichiometry",
    "Chemical equilibrium",
    "Acids, bases, salts",
    "Redox and electrochemistry",
    "Organic chemistry: hydrocarbons, functional groups",
    "Industrial chemistry",
  ],

  // ── INDIA ──────────────────────────────────────────────────────────────────
  "IN_math_Class 12": [
    "Relations and functions",
    "Inverse trigonometric functions",
    "Matrices",
    "Determinants",
    "Continuity and differentiability",
    "Applications of derivatives",
    "Integrals (indefinite and definite)",
    "Applications of integrals",
    "Differential equations",
    "Vector algebra",
    "Three-dimensional geometry",
    "Linear programming",
    "Probability (Bayes' theorem)",
  ],
  "IN_physics_Class 12": [
    "Electrostatics, Gauss's law",
    "Capacitance",
    "Current electricity",
    "Magnetic effects of current",
    "Electromagnetic induction",
    "Alternating current",
    "Electromagnetic waves",
    "Ray optics, optical instruments",
    "Wave optics, interference, diffraction",
    "Dual nature of matter and radiation",
    "Atoms (Bohr model)",
    "Nuclei",
    "Semiconductor electronics",
  ],
  "IN_chemistry_Class 12": [
    "Solid state",
    "Solutions and colligative properties",
    "Electrochemistry",
    "Chemical kinetics",
    "Surface chemistry",
    "p-block, d-block, f-block elements",
    "Coordination compounds",
    "Haloalkanes and haloarenes (SN1/SN2)",
    "Alcohols, phenols, ethers",
    "Aldehydes, ketones, carboxylic acids",
    "Amines",
    "Biomolecules, polymers",
  ],
  "IN_informatics_Class 12": [
    "Python programming review",
    "Data structures: lists, tuples, dictionaries",
    "Stacks and queues",
    "File handling",
    "Functions and recursion",
    "Sorting (bubble, insertion, selection)",
    "Searching (linear, binary)",
    "SQL: DDL, DML, joins",
    "Computer networks (TCP/IP, topologies)",
    "Society, law, and ethics",
  ],

  // ── CHINA ──────────────────────────────────────────────────────────────────
  "CN_math_高三 (Gaokao)": [
    "集合与逻辑 (Sets and logic)",
    "函数 (Functions)",
    "三角函数 (Trigonometric functions)",
    "数列 (Sequences and series)",
    "不等式 (Inequalities)",
    "导数及其应用 (Derivatives and applications)",
    "立体几何 (Solid geometry)",
    "解析几何 (Analytic geometry — circles, conics)",
    "概率与统计 (Probability and statistics)",
    "排列组合与二项式定理 (Permutations, combinations, binomial)",
  ],
  "CN_physics_高三 (Gaokao)": [
    "运动学 (Kinematics)",
    "牛顿运动定律 (Newton's laws)",
    "曲线运动 (Curvilinear motion)",
    "万有引力与航天 (Gravitation and spaceflight)",
    "机械能守恒 (Conservation of energy)",
    "动量守恒 (Momentum conservation)",
    "热学 (Thermodynamics, kinetic theory)",
    "静电场 (Electrostatics)",
    "恒定电流 (Steady current)",
    "磁场 (Magnetic field)",
    "电磁感应 (Electromagnetic induction)",
    "光学与近代物理 (Optics and modern physics)",
  ],
  "CN_chemistry_高三 (Gaokao)": [
    "原子结构与元素周期律",
    "化学键与晶体结构",
    "化学反应与能量",
    "化学反应速率与化学平衡",
    "电解质溶液与离子平衡",
    "氧化还原反应",
    "电化学 (原电池, 电解池)",
    "有机化学 (烃, 醇, 醛, 酸, 酯)",
    "实验化学",
  ],

  // ── JAPAN ──────────────────────────────────────────────────────────────────
  "JP_math_高3 (共通テスト)": [
    "数学I: 数と式, 図形と計量",
    "数学II: 三角関数, 指数・対数",
    "数学III: 極限",
    "数学III: 微分法",
    "数学III: 積分法",
    "数学III: 複素数平面",
    "数学A: 場合の数と確率",
    "数学A: 整数の性質",
    "数学B: 数列",
    "数学B: ベクトル",
    "数学C: 平面上の曲線",
  ],
  "JP_physics_高3 (共通テスト)": [
    "力学: 運動と力",
    "力学: 運動量とエネルギー",
    "力学: 円運動と単振動",
    "熱力学",
    "波動: 波の性質, 音, 光",
    "電磁気: 電場と電位",
    "電磁気: 電流と磁場",
    "電磁気: 電磁誘導",
    "原子: 光電効果, ボーア模型",
    "原子核: 放射性崩壊",
  ],
  "JP_chemistry_高3 (共通テスト)": [
    "物質の構成と化学結合",
    "物質の状態 (気体, 液体, 固体)",
    "化学反応とエネルギー",
    "反応速度と化学平衡",
    "酸と塩基, pH",
    "酸化還元と電池",
    "無機物質",
    "有機化合物 (脂肪族, 芳香族)",
    "高分子化合物",
  ],
  "JP_informatics_高3 (共通テスト)": [
    "情報社会と情報倫理",
    "コンピュータの仕組み",
    "アルゴリズムとプログラミング (Python)",
    "データの表現 (二進法, 文字コード)",
    "ネットワークとセキュリティ",
    "データベース基礎",
    "問題解決とモデル化",
  ],

  // ── SOUTH KOREA ────────────────────────────────────────────────────────────
  "KR_math_고3 (수능)": [
    "지수함수와 로그함수",
    "삼각함수",
    "수열 (등차, 등비, 점화식)",
    "수열의 극한",
    "함수의 극한과 연속",
    "미분법 (다항함수, 초월함수)",
    "적분법 (다항함수, 초월함수)",
    "확률과 통계: 경우의 수",
    "확률 (조건부, 독립)",
    "통계 (이항분포, 정규분포)",
    "기하: 이차곡선, 평면벡터, 공간도형",
  ],
  "KR_physics_고3 (수능)": [
    "역학과 에너지",
    "운동량과 충돌",
    "유체와 열역학",
    "전자기학: 전기장, 전류",
    "전자기 유도",
    "파동과 정보통신",
    "빛과 물질의 이중성",
    "현대물리: 상대성이론",
    "원자와 원자핵",
  ],
  "KR_chemistry_고3 (수능)": [
    "화학의 첫걸음",
    "원자의 세계",
    "화학결합과 분자의 세계",
    "역동적인 화학반응",
    "산화-환원 반응과 전기화학",
    "물의 자동이온화와 pH",
    "산-염기 평형",
    "화학평형",
    "반응속도",
    "유기화학",
  ],

  // ── BRAZIL ─────────────────────────────────────────────────────────────────
  "BR_math_3º ano EM (ENEM)": [
    "Funções (afim, quadrática, exponencial, logarítmica)",
    "Progressões aritméticas e geométricas",
    "Trigonometria",
    "Geometria plana e espacial",
    "Geometria analítica",
    "Análise combinatória",
    "Probabilidade",
    "Estatística (média, mediana, desvio)",
    "Matrizes e sistemas lineares",
    "Números complexos",
  ],
  "BR_physics_3º ano EM (ENEM)": [
    "Cinemática",
    "Dinâmica (leis de Newton, g = 10 m/s²)",
    "Energia e trabalho",
    "Termologia, calorimetria",
    "Termodinâmica",
    "Óptica geométrica",
    "Ondulatória",
    "Eletrostática",
    "Eletrodinâmica",
    "Eletromagnetismo",
    "Física moderna (introdução)",
  ],
  "BR_chemistry_3º ano EM (ENEM)": [
    "Estequiometria",
    "Soluções e concentrações",
    "Termoquímica",
    "Cinética química",
    "Equilíbrio químico, pH",
    "Eletroquímica (pilhas, eletrólise)",
    "Química orgânica: funções e nomenclatura",
    "Reações orgânicas (tipos gerais)",
    "Química ambiental",
  ],

  // ── CANADA ─────────────────────────────────────────────────────────────────
  "CA_math_Grade 12": [
    "Limits and continuity",
    "Derivatives (chain, product, quotient rules)",
    "Applications of derivatives, optimization",
    "Vectors in 2D and 3D",
    "Lines and planes in 3D",
    "Polynomial and rational functions",
    "Exponential and logarithmic functions",
    "Trigonometric functions and identities",
    "Combinatorics and probability",
    "Statistics: distributions",
  ],
  "CA_physics_Grade 12": [
    "Kinematics and dynamics",
    "Energy and momentum",
    "Circular motion and gravitation",
    "Simple harmonic motion",
    "Mechanical waves and sound",
    "Electric field and potential",
    "Magnetic fields and induction",
    "Electromagnetic radiation",
    "Quantum mechanics (intro)",
    "Special relativity",
    "Nuclear physics",
  ],
  "CA_chemistry_Grade 12": [
    "Thermochemistry (ΔH, Hess)",
    "Reaction rates and kinetics",
    "Chemical equilibrium",
    "Acid-base equilibria, pH, Ka, Kb",
    "Solubility equilibria, Ksp",
    "Thermodynamics (ΔG, ΔS)",
    "Electrochemistry, redox",
    "Organic chemistry: nomenclature",
    "Organic reaction mechanisms (SN1, SN2)",
    "Polymers and biochemistry",
  ],
  "CA_informatics_Grade 12": [
    "Object-oriented programming",
    "Algorithm design and analysis",
    "Recursion",
    "Data structures (lists, stacks, queues, trees)",
    "Sorting and searching",
    "File I/O and persistence",
    "Software development lifecycle",
    "Networking basics",
  ],

  // ── AUSTRALIA ──────────────────────────────────────────────────────────────
  "AU_math_Year 12 (ATAR)": [
    "Functions and graphs",
    "Trigonometric functions and identities",
    "Differential calculus",
    "Integral calculus",
    "Differential equations (Specialist)",
    "Vectors in 2D and 3D",
    "Complex numbers (Specialist)",
    "Proof techniques (Specialist)",
    "Probability distributions (binomial, normal)",
    "Statistical inference",
  ],
  "AU_physics_Year 12 (ATAR)": [
    "Projectile and circular motion",
    "Gravitation and orbits",
    "Special relativity",
    "Electric and magnetic fields",
    "Electromagnetic induction",
    "Light and quantum theory",
    "Atomic and nuclear physics",
    "Particle physics (introduction)",
  ],
  "AU_chemistry_Year 12 (ATAR)": [
    "Reaction rates and equilibrium",
    "Acids and bases, pH",
    "Redox and electrochemistry",
    "Organic chemistry and mechanisms",
    "Polymers and synthesis",
    "Analytical techniques (chromatography, spectroscopy)",
  ],
  "AU_informatics_Year 12 (ATAR)": [
    "Programming in Python",
    "Algorithms and complexity (Big-O — VIC Algorithmics)",
    "Data structures",
    "Databases and SQL",
    "Networking and security",
    "Software development project",
  ],
};

function normalize(list: Topic[]): TopicEntry[] {
  return list.map((t) => (typeof t === "string" ? { label: t, limits: "" } : t));
}

export function topicsFor(
  countryCode: string,
  subject: Subject,
  gradeLevel?: string,
  section?: string,
): TopicEntry[] {
  const c = countryCode.toUpperCase();
  if (gradeLevel && section) {
    const sectional = TOPICS[`${c}_${subject}_${gradeLevel}_${section}`];
    if (sectional?.length) return normalize(sectional);
  }
  if (gradeLevel) {
    const byLevel = TOPICS[`${c}_${subject}_${gradeLevel}`];
    if (byLevel?.length) return normalize(byLevel);
  }
  const fallback = TOPICS[`${c}_${subject}`];
  return fallback?.length ? normalize(fallback) : [];
}

/** The string actually sent as the `topic` field on API requests. */
export function topicValue(t: TopicEntry): string {
  return t.limits ? `${t.label} — ${t.limits}` : t.label;
}
